"""Constants for the ES-32MD Scale BLE integration."""

DOMAIN = "es32md_scale"

CONF_SCALE_MAC = "scale_mac"
CONF_WEIGHT_UNIT = "weight_unit"
CONF_HEIGHT_UNIT = "height_unit"
CONF_USERS = "users"
CONF_USER_NAME = "name"
CONF_USER_SLUG = "slug"
CONF_USER_HEIGHT = "height"
CONF_USER_BIRTH_DATE = "birth_date"
CONF_USER_GENDER = "gender"
CONF_USER_IS_ATHLETE = "is_athlete"
CONF_USER_WEIGHT_RANGE_MIN = "weight_range_min"
CONF_USER_WEIGHT_RANGE_MAX = "weight_range_max"
CONF_USER_NOTIFY_TARGET = "notify_target"
CONF_USER_AUTO_ASSIGN = "auto_assign"
CONF_CONFIRMATION_TIMEOUT = "confirmation_timeout"
CONF_USER_GARMIN_EMAIL = "garmin_email"
CONF_USER_GARMIN_PASSWORD = "garmin_password"

WEIGHT_UNIT_KG = "kg"
WEIGHT_UNIT_LBS = "lbs"
HEIGHT_UNIT_CM = "cm"
HEIGHT_UNIT_IN = "in"

MANUFACTURER_ID = 0xFFFF
RENPHO_HEADER = bytes([0xAA, 0xBB])

PAYLOAD_STATUS_BYTE = 7
PAYLOAD_WEIGHT_LOW = 9
PAYLOAD_WEIGHT_HIGH = 10

STATUS_STARTUP = 0x05
STATUS_MEASURING = 0x04
STATUS_STABLE = 0x25
STATUS_STABLE_OFFLINE = 0x24
STATUS_OFFLINE_REPLAY = 0x64

STABLE_STATUSES = {STATUS_STABLE, STATUS_STABLE_OFFLINE, STATUS_OFFLINE_REPLAY}

PAYLOAD_DATA_LENGTH = 16
MAC_HEADER_LENGTH = 8

DATA_COORDINATOR = "coordinator"
DATA_SENSORS = "sensors"
DATA_PENDING = "pending_measurements"

ACTION_CONFIRM_PREFIX = "es32md_confirm_"
ACTION_DENY_PREFIX = "es32md_deny_"

DEFAULT_CONFIRMATION_TIMEOUT = 300
